var shopping=[
    {
        "id":'1',
        "src":'img/1496210830044.jpg',
        "special":'性价比王牌',
        "name":'小米手机',
        "phone":[
            {
                "title":'颜色',
                "special":[
                    {"titlespecial":"红色"},
                    {"titlespecial":"黄色"},
                    {"titlespecial":"蓝色"},
                    {"titlespecial":"银色"}
                ]
            },
            {
                "title":'内存',
                "special":[
                    {"titlespecial":"2G"},
                    {"titlespecial":"4G"},
                    {"titlespecial":"6G"},
                    {"titlespecial":"8G"}
                ]
            },
            {
                "title":'存储',
                "special":[
                    {"titlespecial":"16G"},
                    {"titlespecial":"32G"},
                    {"titlespecial":"64G"},
                    {"titlespecial":"128G"}
                ]
            }

        ],
        "commodity":[
            {
                "title":'红色2G16G',
                "value":'3000',
                "inventory":'30'
            },
            {
                "title":'黄色4G32G',
                "value":'3500',
                "inventory":'22'
            },
            {
                "title":'蓝色6G64G',
                "value":'4000',
                "inventory":'55'
            },
            {
                "title":'银色8G128G',
                "value":'8000',
                "inventory":'29'
            },
            {
                "title":'红色2G64G',
                "value":'4500',
                "inventory":'2'
            }
        ]
    }
]