var indet=[
    {   
        "worksheet":'001',
        "merchant":'朱鹏店铺02',
        "buyerphone":'12345678901',
        "commodity":[
            {
                "src":"img_buyer/1495876158498.png",
                "commname":'小米手机',
                "type":'国产好手机',
                "style":'23',
                "value":'1999'
            },
            {
                "src":"img_buyer/1495876158498.png",
                "commname":'苹果手机',
                "type":'高档手机',
                "style":'11',
                "value":'1999'
            }
        ],
        "buyer":'小王'
    },
    {
        "worksheet":'001',
        "merchant":'朱鹏店铺01',
        "buyerphone":'12345678901',
        "commodity":[
            {
                "src":"img_buyer/1495876158498.png",
                "commname":'三枪内裤',
                "type":'世界名牌内裤',
                "style":'31',
                "value":'9999'
            }
            
        ],
        "buyer":'小狗'
    }
]

var mycommod=[
    {
        "src":'img_buyer/1495876158498.png',
        "commodname":'01苹果',
        "style":'512G白色',
        "commodvalue":'8999',
        "number":'19',
        "buyername":'小王'
    },
    {
        "src":'img_buyer/1495876158498.png',
        "commodname":'09华为',
        "style":'512G黑色',
        "commodvalue":'18999',
        "number":'89',
        "buyername":'老王'
    }
]

var  shopcart=[
    {
        "src":'img_buyer/1495876158498.png',
        "commodname":'阳光采购',
        "type":'好多不想写',
        "number":'12',
        "product":'采用标准化采购流程哈哈哈哈哈',
        "money":'10'
    },
    {
        "src":'img_buyer/1495876158498.png',
        "commodname":'阳光采购',
        "type":'好多不想写',
        "number":'12',
        "product":'采用标准化采购流程哈哈哈哈哈',
        "money":'30'
    }
]